
/**
 * TODO: Insert description here. (generated by sreenivasa)
 */
public class dataTypesVariablesArrays {

  public static void main(String args[]){
    //Primitive Types - Integers, Float, Chars, Boolean
    // Integers - bye, short, int and long.
    // Floating points - float , double.
    int lightspeed;
    long days; 
    long seconds;
    long distance;
    lightspeed = 18600;    
    days = 1000;
    seconds = days * 24 * 60 * 60;
    distance = lightspeed * seconds;
    System.out.print("In " + days );
    System.out.print(" days light will travel about ");
    System.out.println(distance + " miles");
    //Double Data Type:
    double hightemp, lowtemp;
    hightemp = 66.7875;
    lowtemp = 15.668;
    System.out.println("Hightemp:" +hightemp +"   lowtep::" +lowtemp);
    // Finding area of circle
    double pi, r, a;
    boolean bo;
    pi=3.1416;
    r = 10.8;
    a = pi*r*r;
    System.out.println("Area of Circle ::" +a);
    bo = false;
    System.out.println("B value::" +bo);

    // Literals::
    System.out.println("****************** LITERALS *************");
    double c = Math.sqrt(r+r);
    System.out.println("Dynamic Variable" +c);
    //Type Conversion and Casting
    int t = 10;
    byte b;
    b = (byte) t;
    System.out.println("Cating of int into float " +b);
 // Literals::
    System.out.println("****************** ARRAYS *************");
    
    int month_days[];
    month_days = new int[12];
    month_days[1] = 31;
    
    System.out.println("April Has different new way" +month_days[1] + "Days");
    
    // Another way to array
    int monthdays[]={31, 28, 31, 30, 31, 30, 31, 31, 30, 31,30, 31};
    System.out.println("April Has diffrent way" +monthdays[1] + "Days"); 
    System.out.println("***Finding Average of number in an array***");
    double numarray[]={10.5,2.5,3.5,6.8};
    double result = 0;
    
    for (int i=0;i<numarray.length;i++){
      result = result + numarray[i];
      double avg = result/numarray.length;
          System.out.println("Avg of numbers:" +avg);
    }
    
    // Two Dimensional Array
    int twoD[][] = new int[4][5];
    int i,j,k = 0;
    
    for (i=0;i<4;i++)
      for(j=0;j<5;j++){
        twoD[i][j] = k;
        k++;
      }
    for(i=0; i<4; i++) {
      for(j=0; j<5; j++)
      System.out.print(twoD[i][j] + " ");
      System.out.println();
      }
  }
}

