
/**
 * TODO: Insert description here. (generated by sreenivasa)
 */
public class javaOperators {
  
  public static void main (String args[]){
    double y = 42564557.25215;
    
    System.out.println("Y mod 1000000 = " + y % 10);
    
  }

}

