
/**
 * TODO: Insert description here. (generated by sreenivasa)
 */
public class MaxOfTwoNumbers {
  
  public static void main (String args[]){
    // take two number from command prompt
    
     int[] i = {6};
     int[] j = {10};
     
    //int i = Integer.parseInt(args[0]);
    //int j = Integer.parseInt(args[1]);
    
    if (i[0]>j[0])
      System.out.println(i[0]+" is greater than " +j[0]);
    else 
      System.out.print(j[0]+" is greater than " +i[0]);    
  }

}

