
/**
 * TODO: Insert description here. (generated by sreenivasa)
 */
class ABC{
  public void disp(){
    System.out.println("disp() method of PARENT class");
  }
  public void abc(){
    System.out.println("abc() method of PARENT class");
  }
}

public class MethodOverride1 extends ABC{
  public void disp(){
    System.out.println("disp() method of CHILD class");
  }
  public void xyz(){
    System.out.println("xyz() method of CHILD class");
  }
  
  public static void main (String args[]){
    //Parent class reference to child class object
    ABC obj = new MethodOverride1();
    obj.disp();
    obj.abc();
  }
}

