
/**
 * TODO: Insert description here. (generated by sreenivasa)
 */

class Human{
  public void eat(){
    System.out.println("Huma is eating");
  }
}

//class Boy extends Human{
//  @Override  
//  public void eat(){
//    System.out.println("Boy is eating"); 
//  }
//}  
public class MethodOverriding extends Human{
  @Override
  public void eat(){
    System.out.println("Boy is eating"); 
  }
    
   public static void main (String args[]){
     MethodOverriding obj = new MethodOverriding();
   obj.eat();   
  }

}

