
/**
 * TODO: Insert description here. (generated by sreenivasa)
 */
public class SreeFirstProgramTest {
  
  public static void main(String[] args) {
    System.out.println("Sree Test Program");
    
  } 
}

